repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npm run lint:fix --
        language: system
        files: \.(js)$
        exclude: ^eslint.config\.js$
        types: [file]
        pass_filenames: true

      - id: prettier
        name: prettier
        entry: npm run format --
        language: system
        files: \.(js|json|md|yaml|yml)$
        types: [file]
        pass_filenames: true
